# Generated by Django 5.0.3 on 2024-03-29 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olymp', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('country1', models.CharField(max_length=200, null=True)),
                ('final_result', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='bet_amt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Betting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pred_coun', models.CharField(max_length=200, null=True)),
                ('bet_reg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bett_to_regis', to='olymp.registration')),
                ('bet_playy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bett_to_plays', to='olymp.playss')),
            ],
        ),
    ]
