# Generated by Django 5.0.3 on 2024-04-12 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olymp', '0005_playss_registration_bet_amt_betting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Betting_admin_amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=200, null=True)),
                ('bet_playy_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bett_to_plays_admin', to='olymp.playss')),
                ('bet_reg_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bett_to_regis_admin', to='olymp.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Betting_user_amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=200, null=True)),
                ('bet_playy_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bett_to_plays_user', to='olymp.playss')),
                ('bet_reg_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bett_to_regis_user', to='olymp.registration')),
            ],
        ),
    ]
