# Generated by Django 5.0.3 on 2024-04-13 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olymp', '0006_betting_admin_amount_betting_user_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bankk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=200, null=True)),
                ('bank_reg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_to_regis', to='olymp.registration')),
            ],
        ),
    ]
